import * as THREE from './vendor/three.module.js';
export const HEROES=[
  {name:'奥克塔维娅',bpm:120,hp:100,speed:6.2,damage:11,color:'#c3f584',symbol:'◈',track:'Emerald Afterglow',genre:'MELODIC HOUSE',skill:'音符追踪 · 均衡而精准'},
  {name:'阿玛雅',bpm:132,hp:90,speed:7,damage:9,color:'#f6c58c',symbol:'ϟ',track:'Midnight Sidewalk',genre:'FUTURE FUNK',skill:'散射音符 · 灵动的放克节奏'},
  {name:'回声',bpm:108,hp:120,speed:5.7,damage:14,color:'#c6b2f4',symbol:'✳',track:'Violet Reverie',genre:'SYNTHWAVE',skill:'穿透长音 · 深沉而有力'}
];
export const UPGRADES=[
  {id:'bass',name:'低频引力',icon:'♩',tag:'招募 · 贝斯手',description:'贝斯手加入乐队，穿透低音贯穿敌群；音乐新增低频声部。',effect:'每 2 拍 · 穿透 3 个目标',max:1},
  {id:'strings',name:'星弦回响',icon:'♬',tag:'招募 · 提琴手',description:'提琴手加入乐队，交织追踪旋律；音乐新增流动的高音声部。',effect:'每 2 拍 · 双重追踪音符',max:1},
  {id:'drums',name:'心跳引擎',icon:'◉',tag:'招募 · 鼓手',description:'鼓手加入乐队，每个重拍用范围冲击推开近身敌人。',effect:'每 4 拍 · 范围冲击',max:1},
  {id:'power',name:'过载音箱',icon:'▥',tag:'强化 · 输出',description:'将音量推向极限，全体乐队成员造成更高伤害。',effect:'全队伤害 +18%',max:4},
  {id:'multishot',name:'立体声场',icon:'⋔',tag:'强化 · 弹幕',description:'主旋律分裂出额外的音符，覆盖更多虚空生物。',effect:'主角额外发射 1 枚音符',max:2},
  {id:'barrier',name:'音障共振',icon:'◎',tag:'强化 · 节奏',description:'合拍转向与精准重音释放更大的音障，让敌群无法靠近。',effect:'音障伤害 +8 · 半径 +0.6',max:3},
  {id:'tempo',name:'轻盈切分',icon:'↗',tag:'强化 · 机动',description:'用更轻盈的步伐穿梭战场，闪避更快恢复。',effect:'移动速度 +9% · 闪避冷却 −0.3s',max:3},
  {id:'health',name:'温暖和弦',icon:'✚',tag:'强化 · 生存',description:'稳定的和弦守护着你。立即回复生命，并提高生命上限。',effect:'生命上限 +25 · 回复 30',max:3},
  {id:'magnet',name:'余音收集器',icon:'⌁',tag:'强化 · 成长',description:'更远处的音符自动飞向你，让每一段旋律都成为力量。',effect:'拾取范围 +2 · 经验 +15%',max:3},
  {id:'energy',name:'安可时刻',icon:'✳',tag:'强化 · 共鸣',description:'合拍演奏和净化敌人积累更多共鸣，更频繁释放爆发。',effect:'能量获取 +30% · 立即 +20 能量',max:3},
  {id:'orbit',name:'环绕立体声',icon:'✧',tag:'强化 · 护卫',description:'环绕乐队的音符持续切割附近的虚空生物。',effect:'新增 2 枚环绕音符',max:2},
  {id:'heal',name:'一段间奏',icon:'♡',tag:'补给 · 恢复',description:'深呼吸，听见自己的心跳。恢复生命后继续演奏。',effect:'立即回复 45 生命',max:99}
];
const TAU=Math.PI*2,clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const rand=(a,b)=>a+Math.random()*(b-a);
export class Game {
  constructor(world,audio,emit=()=>{}){this.world=world;this.audio=audio;this.emit=emit;this.state='menu';this.keys=new Set();this.stick={x:0,z:0};this.heroIndex=0;this.projectiles=[];this.gems=[];this.enemies=[];this.friends=[];this.pointer=null;this.lastAim=0;this.resetMenu();}
  resetMenu(){this.state='menu';this.audio.stop();this.world.clear();this.enemies=[];this.projectiles=[];this.gems=[];this.friends=[];this.player=this.world.createActor('hero',this.heroIndex);this.player.position.set(1,.23,2.2);this.player.angle=-.3;for(let i=0;i<3;i++){const a=this.world.createActor('friend',(i+1)%4);a.position.set(2.2+i*.6,.23,3.5+i*.7);a.angle=-.5;this.friends.push({actor:a,type:['guitar','bass','strings'][i]});}this.keys.clear();this.emit('menu');}
  selectHero(i){this.heroIndex=i;this.player.hero=i;this.world.heroColor=HEROES[i].color;}
  async start(){if(this.starting)return;this.starting=true;try{this.world.clear();const h=HEROES[this.heroIndex];this.config=h;this.time=0;this.hp=this.maxHp=h.hp;this.speed=h.speed;this.damage=h.damage;this.level=1;this.xp=0;this.nextXp=6;this.kills=0;this.combo=0;this.bestCombo=0;this.score=0;this.energy=0;this.invincible=1.5;this.dashTimer=0;this.dashCd=0;this.dashDirection=new THREE.Vector3(0,0,1);this.barrierCd=0;this.manualCd=0;this.perfects=0;this.lastMoveAngle=null;this.lastTurnTime=-1;this.lastManualBeat=-1;this.spawnClock=0;this.stage=-1;this.bossSpawned=false;this.boss=null;this.enemies=[];this.projectiles=[];this.gems=[];this.friends=[];this.upgrades={};this.upgradeChoices=[];this.keys.clear();this.stick={x:0,z:0};this.inputDirection=new THREE.Vector3(0,0,1);this.player=this.world.createActor('hero',this.heroIndex);this.player.position.set(0,.23,1);this.addFriend('guitar');this.fallbackBeat=-1;await this.audio.start(h.bpm,this.heroIndex);this.audio.layers=2;this.state='playing';this.emit('start',h);this.emit('announcement',{small:'CHAPTER 01 / NEON GROVE',title:'让森林听见你的心跳'});for(let i=0;i<4;i++)this.spawnEnemy('normal',i*TAU/4,12);this.emit('stats');}finally{this.starting=false;}}
  addFriend(type){const hero={guitar:1,bass:3,strings:2,drums:0}[type];const a=this.world.createActor('friend',hero);a.position.copy(this.player.position).add(new THREE.Vector3(this.friends.length*.5+1,0,1));a.scale=.86;this.friends.push({actor:a,type});this.audio.layers=Math.min(4,this.friends.length+1);}
  pause(){if(this.state!=='playing')return;this.state='paused';this.keys.clear();this.stick={x:0,z:0};this.audio.pause();this.emit('pause');}
  resume(){if(this.state!=='paused')return;this.state='playing';this.audio.resume();this.emit('resume');}
  moveInput(){const k=this.keys;let x=(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0)+this.stick.x,z=(k.has('KeyS')||k.has('ArrowDown')?1:0)-(k.has('KeyW')||k.has('ArrowUp')?1:0)+this.stick.z;const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}return{x,z};}
  timing(){let phase=this.audio.ctx?this.audio.phase():(this.time*this.config.bpm/60)%1;return Math.min(phase,1-phase)*60/this.config.bpm;}
  performDash(){if(this.state!=='playing'||this.dashCd>0)return false;const d=this.moveInput();if(Math.hypot(d.x,d.z)>.1)this.dashDirection.set(d.x,0,d.z).normalize();else this.dashDirection.copy(this.inputDirection);this.dashTimer=.23;this.dashCd=Math.max(1.25,2.5-(this.upgrades.tempo||0)*.3);this.invincible=Math.max(this.invincible,.35);this.audio.fx('dash');this.world.shockwave(this.player.position,'#bdedc2',1,.3);return true;}
  performPulse(){if(this.state!=='playing'||this.energy<100)return false;this.energy=0;this.invincible=Math.max(this.invincible,1);this.audio.fx('pulse');this.world.shockwave(this.player.position,'#cfff9e',18,1);this.world.shockwave(this.player.position,'#8bedde',13,.8);this.world.burst(this.player.position,'#c8fda5',90,10);this.world.shake=.65;this.projectiles=this.projectiles.filter(p=>!p.enemy);for(const e of [...this.enemies])if(distance(e.actor.position,this.player.position)<15)this.hitEnemy(e,75*(1+(this.upgrades.power||0)*.18),true);this.emit('announcement',{small:'RESONANCE / 100%',title:'共 鸣 爆 发'});return true;}
  manualAttack(){if(this.state!=='playing'||this.manualCd>0)return;this.manualCd=.17;const currentBeat=Math.round((this.audio.ctx?this.audio.now():this.time)*this.config.bpm/60);if(currentBeat===this.lastManualBeat)return;this.lastManualBeat=currentBeat;const timing=this.timing();if(timing<.092){this.combo++;this.perfects++;this.bestCombo=Math.max(this.combo,this.bestCombo);this.energy=clamp(this.energy+3*(1+(this.upgrades.energy||0)*.3),0,100);this.score+=25;this.audio.fx('perfect');this.emit('judge',{text:'PERFECT',kind:'perfect'});this.firePlayer(1.8,true);this.barrier(1);this.world.shake=Math.max(this.world.shake,.12);}
    else if(timing<.16){this.combo++;this.bestCombo=Math.max(this.combo,this.bestCombo);this.energy=clamp(this.energy+1,0,100);this.emit('judge',{text:'GOOD',kind:'good'});this.firePlayer(1.1,false);}
    else{this.combo=0;this.emit('judge',{text:'OFF BEAT',kind:'miss'});this.firePlayer(.45,false);}this.emit('stats');}
  barrier(multiplier=1){if(this.barrierCd>0)return;this.barrierCd=.55;const radius=2.8+(this.upgrades.barrier||0)*.6,damage=(10+(this.upgrades.barrier||0)*8)*multiplier;this.world.shockwave(this.player.position,'#aef5d3',radius,.4);for(const e of [...this.enemies]){if(distance(e.actor.position,this.player.position)<radius){this.hitEnemy(e,damage,true);const dir=e.actor.position.clone().sub(this.player.position).normalize();e.actor.position.addScaledVector(dir,e.type==='boss'?.2:1.4);}}this.projectiles=this.projectiles.filter(p=>!p.enemy||distance(p,this.player.position)>radius);}
  nearest(pos,count=1){return this.enemies.filter(e=>!e.dead&&distance(e.actor.position,pos)<16).sort((a,b)=>distance(a.actor.position,pos)-distance(b.actor.position,pos)).slice(0,count);}
  shoot(pos,target,damage,opts={}){if(!target||this.projectiles.length>450)return;const dir=target.actor.position.clone().sub(pos).normalize(),angle=opts.offset||0,ca=Math.cos(angle),sa=Math.sin(angle),speed=opts.speed||16;this.projectiles.push({x:pos.x,z:pos.z,y:.9,vx:(dir.x*ca-dir.z*sa)*speed,vz:(dir.x*sa+dir.z*ca)*speed,life:1.5,damage:damage*(1+(this.upgrades.power||0)*.18),size:opts.size||.13,color:opts.color||this.config.color,target:opts.homing===false?null:target,pierce:opts.pierce||0,critical:opts.critical||false,hitIds:new Set(),enemy:false});}
  firePlayer(mult=1,critical=false){const targets=this.nearest(this.player.position,3);if(!targets.length)return;const main=this.pointer&&this.time-this.lastAim<4?targets.reduce((a,b)=>distance(a.actor.position,this.pointer)<distance(b.actor.position,this.pointer)?a:b):targets[0];const count=1+(this.upgrades.multishot||0)+(this.heroIndex===1?1:0);for(let i=0;i<count;i++)this.shoot(this.player.position,targets[i%targets.length]||main,this.damage*mult,{critical,pierce:this.heroIndex===2?2:0,offset:(i-(count-1)/2)*.1,size:critical?.19:.13,homing:this.heroIndex!==2,color:this.config.color});}
  onBeat(beat){this.world.beat(beat%4===0);this.emit('beat',beat);this.firePlayer(beat%4===0?1.22:1);for(const f of this.friends){if(f.type==='guitar'&&beat%2===0){const e=this.nearest(f.actor.position)[0];if(e)this.shoot(f.actor.position,e,8,{color:'#f6aecc'});}if(f.type==='bass'&&beat%2===1){const e=this.nearest(f.actor.position)[0];if(e)this.shoot(f.actor.position,e,14,{color:'#80e6de',pierce:3,homing:false,size:.18});}if(f.type==='strings'&&beat%2===0){for(const e of this.nearest(f.actor.position,2))this.shoot(f.actor.position,e,8,{color:'#c6abff',speed:13});}if(f.type==='drums'&&beat%4===0){this.world.shockwave(f.actor.position,'#efce8e',4,.45);for(const e of [...this.enemies])if(distance(e.actor.position,f.actor.position)<4)this.hitEnemy(e,15,false);}}}
  spawnEnemy(type='normal',angle=Math.random()*TAU,radius=rand(13,17)){if(this.enemies.length>=65)return;const p=this.player.position;let x=clamp(p.x+Math.sin(angle)*radius,-21,21),z=clamp(p.z+Math.cos(angle)*radius,-18,18);if(Math.hypot(x-p.x,z-p.z)<8){x=clamp(p.x-Math.sin(angle)*radius,-21,21);z=clamp(p.z-Math.cos(angle)*radius,-18,18);}const a=this.world.createActor(type);a.position.set(x,.23,z);const stats={normal:[19,2.25,9,1],charger:[25,2.55,11,2],ranged:[27,1.65,8,2],tank:[58,1.5,15,4],boss:[820,1.6,16,50]}[type];const scale=type==='boss'?1:1+this.time/600;const e={actor:a,type,hp:stats[0]*scale,maxHp:stats[0]*scale,speed:stats[1],damage:stats[2],xp:stats[3],cooldown:rand(1.5,3),attackTimer:0,chargeTime:0,chargeDir:new THREE.Vector3(),dead:false,id:Math.random(),orbitCd:0,phase:0,summonCd:7};this.enemies.push(e);this.world.burst(a.position,type==='boss'?'#eb8abd':'#9b758b',type==='boss'?50:5,2);return e;}
  spawnBoss(){this.bossSpawned=true;for(const e of [...this.enemies])this.killEnemy(e,false);this.collectAllGems();if(this.state!=='playing')return;this.boss=this.spawnEnemy('boss',Math.PI,11);this.boss.actor.scale=1.35;this.boss.maxHp=this.boss.hp=2800;this.world.shake=.6;this.world.shockwave(this.boss.actor.position,'#e58bbd',14,1.2);this.emit('announcement',{small:'FINAL MOVEMENT / THE SILENT ONE',title:'寂静之心，已经苏醒'});this.emit('boss');}
  enemyShot(e,angle,speed=4.9){if(this.projectiles.length>450)return;this.projectiles.push({x:e.actor.position.x,z:e.actor.position.z,y:.8,vx:Math.sin(angle)*speed,vz:Math.cos(angle)*speed,life:6,damage:e.type==='boss'?9:e.damage,size:e.type==='boss'?.22:.18,color:'#f490b7',enemy:true});}
  updateEnemies(dt){const pp=this.player.position;
    for(const e of [...this.enemies]){if(e.dead)continue;const a=e.actor,d=distance(a.position,pp);const dir=pp.clone().sub(a.position);dir.y=0;dir.normalize();a.angle=Math.atan2(dir.x,dir.z);e.cooldown-=dt;e.orbitCd=Math.max(0,e.orbitCd-dt);a.walk+=dt*e.speed;
      if(e.type==='boss'){
        e.summonCd-=dt;if(e.summonCd<=0){e.summonCd=7;this.spawnEnemy('normal');this.spawnEnemy('normal');}
        if(e.attackTimer>0){e.attackTimer-=dt;if(e.attackTimer<=0){if(e.phase%3===0){this.world.shockwave(e.attackPos,'#ef85b6',3.6,.5);if(distance(e.attackPos,pp)<3.6)this.hurt(20);this.world.burst(e.attackPos,'#ef8ab3',30,5);}else if(e.phase%3===1){e.chargeTime=.85;}else{const toPlayer=Math.atan2(pp.x-a.position.x,pp.z-a.position.z);for(let i=0;i<16;i++){const ang=i*TAU/16;let diff=Math.atan2(Math.sin(ang-toPlayer),Math.cos(ang-toPlayer));if(Math.abs(diff)>.38)this.enemyShot(e,ang,4.5);}}e.phase++;e.cooldown=e.hp<e.maxHp/2?2.2:3;}}
        else if(e.chargeTime>0){e.chargeTime-=dt;a.position.addScaledVector(e.chargeDir,dt*10);this.world.burst(a.position,'#e888b2',1,1);}
        else if(e.cooldown<=0){e.attackTimer=.9;e.attackPos=pp.clone();if(e.phase%3===0)this.world.danger(e.attackPos,3.6,.9);else if(e.phase%3===1){e.chargeDir.copy(dir);const end=a.position.clone().addScaledVector(dir,10);end.y=.3;const start=a.position.clone();start.y=.3;this.world.beam(start,end,'#f17caf',.9,.19);}else this.world.danger(a.position,3,.9);}
        else if(d>4)a.position.addScaledVector(dir,e.speed*dt);
      }else if(e.type==='charger'){
        if(e.attackTimer>0){e.attackTimer-=dt;if(e.attackTimer<=0)e.chargeTime=.7;}
        else if(e.chargeTime>0){e.chargeTime-=dt;a.position.addScaledVector(e.chargeDir,dt*7);}
        else if(e.cooldown<=0&&d<10){e.cooldown=3.6;e.attackTimer=.6;e.chargeDir.copy(dir);const from=a.position.clone(),to=from.clone().addScaledVector(dir,6);from.y=to.y=.3;this.world.beam(from,to,'#ea9588',.6,.08);}
        else a.position.addScaledVector(dir,e.speed*dt);
      }else if(e.type==='ranged'){
        if(e.attackTimer>0){e.attackTimer-=dt;if(e.attackTimer<=0){this.enemyShot(e,Math.atan2(e.chargeDir.x,e.chargeDir.z));e.cooldown=2.8;}}
        else if(e.cooldown<=0&&d<15){e.attackTimer=.6;e.chargeDir.copy(dir);const from=a.position.clone(),to=pp.clone();from.y=to.y=.31;this.world.beam(from,to,'#e79cca',.6,.045);}
        else if(d>7.5)a.position.addScaledVector(dir,e.speed*dt);else if(d<5)a.position.addScaledVector(dir,-e.speed*.6*dt);
      }else a.position.addScaledVector(dir,e.speed*dt);
      a.position.x=clamp(a.position.x,-22,22);a.position.z=clamp(a.position.z,-19,19);if(this.world.constrain?.(a.position,e.type==='boss'?1:.3)){a.position.x+=dir.z*e.speed*dt;a.position.z-=dir.x*e.speed*dt;this.world.constrain(a.position,e.type==='boss'?1:.3);}
      if(d<(e.type==='boss'?1.65:e.type==='tank'?.95:.70))this.hurt(e.damage);
      if(this.upgrades.orbit&&e.orbitCd<=0){for(let i=0;i<this.upgrades.orbit*2;i++){const angle=this.time*2.4+i*TAU/(this.upgrades.orbit*2),orb={x:pp.x+Math.sin(angle)*2.2,z:pp.z+Math.cos(angle)*2.2};if(distance(orb,a.position)<.75){e.orbitCd=.4;this.hitEnemy(e,10,false);break;}}}
    }
    // A gentle separation pass prevents monsters becoming one unreadable stack.
    for(let i=0;i<this.enemies.length;i++)for(let j=i+1;j<this.enemies.length;j++){const a=this.enemies[i],b=this.enemies[j];if(a.type==='boss'||b.type==='boss')continue;let dx=a.actor.position.x-b.actor.position.x,dz=a.actor.position.z-b.actor.position.z;const d=Math.hypot(dx,dz);if(d>0&&d<.65){const push=(.65-d)*dt*2;dx/=d;dz/=d;a.actor.position.x+=dx*push;a.actor.position.z+=dz*push;b.actor.position.x-=dx*push;b.actor.position.z-=dz*push;}}
  }
  hitEnemy(e,damage,critical=false){if(e.dead)return;e.hp-=damage;e.actor.hit=.075;this.world.burst(e.actor.position,critical?'#e5ffb4':'#b8eac8',critical?7:3,2.5);this.world.label(e.actor.position,Math.round(damage),critical?'critical':'');if(Math.random()<.25)this.audio.fx('hit');if(e.hp<=0)this.killEnemy(e);}
  killEnemy(e,reward=true){if(e.dead)return;e.dead=true;this.world.removeActor(e.actor);const i=this.enemies.indexOf(e);if(i>=0)this.enemies.splice(i,1);this.world.burst(e.actor.position,e.type==='boss'?'#ffc8ed':'#b18cbd',e.type==='boss'?100:12,e.type==='boss'?10:3);if(reward){this.kills++;this.score+=(e.type==='boss'?5000:100)+this.combo*2;this.energy=clamp(this.energy+1.6*(1+(this.upgrades.energy||0)*.3),0,100);if(e.type!=='boss'){if(this.gems.length>170){const closest=this.gems[0];closest.value+=e.xp;}else this.gems.push({x:e.actor.position.x,z:e.actor.position.z,value:e.xp});}}
    if(e.type==='boss'&&reward)this.finish(true);
  }
  hurt(amount){if(this.state!=='playing'||this.invincible>0)return;this.hp=Math.max(0,this.hp-amount);this.invincible=.78;this.combo=0;this.world.shake=.45;this.world.label(this.player.position,'−'+amount,'damage');this.world.burst(this.player.position,'#f0a6b7',15,4);this.audio.fx('hurt');this.emit('hurt');this.emit('stats');if(this.hp<=0)this.finish(false);}
  collectAllGems(){let sum=0;for(const g of this.gems)sum+=g.value;this.gems=[];this.addXp(sum);}
  addXp(value){if(!value)return;this.xp+=value*(1+(this.upgrades.magnet||0)*.15);if(this.xp>=this.nextXp&&this.state==='playing'){this.xp-=this.nextXp;this.level++;this.nextXp=6+Math.floor((this.level-1)*3.8);this.openUpgrade();}}
  openUpgrade(){this.state='upgrade';this.keys.clear();this.stick={x:0,z:0};this.audio.fx('upgrade');this.audio.pause();let pool=UPGRADES.filter(u=>(this.upgrades[u.id]||0)<u.max&&(u.id!=='heal'||this.hp<this.maxHp*.65));let chosen=[];if(this.level===2)chosen=pool.filter(u=>['bass','strings','drums'].includes(u.id));else{if(this.hp<this.maxHp*.4)chosen.push(UPGRADES.find(u=>u.id==='heal'));if(this.level===4&&this.friends.length<3){const f=pool.find(u=>['bass','strings','drums'].includes(u.id));if(f)chosen.push(f);}pool=pool.filter(u=>!chosen.includes(u));while(chosen.length<3&&pool.length)chosen.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);}this.upgradeChoices=chosen;this.emit('upgrade',chosen);}
  chooseUpgrade(index){if(this.state!=='upgrade')return;const u=this.upgradeChoices[index];if(!u)return;this.upgrades[u.id]=(this.upgrades[u.id]||0)+1;if(['bass','strings','drums'].includes(u.id))this.addFriend(u.id);if(u.id==='health'){this.maxHp+=25;this.hp=Math.min(this.maxHp,this.hp+30);}if(u.id==='heal')this.hp=Math.min(this.maxHp,this.hp+45);if(u.id==='tempo')this.speed=this.config.speed*(1+.09*this.upgrades.tempo);if(u.id==='energy')this.energy=Math.min(100,this.energy+20);this.state='playing';this.audio.resume();this.audio.fx('upgrade');this.emit('upgraded',u);this.emit('stats');if(this.xp>=this.nextXp){this.xp-=this.nextXp;this.level++;this.nextXp=6+Math.floor((this.level-1)*3.8);this.openUpgrade();}}
  updateProjectiles(dt){for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i];p.life-=dt;if(p.life<=0||Math.abs(p.x)>30||Math.abs(p.z)>27){this.projectiles.splice(i,1);continue;}if(p.target&&!p.target.dead){const dx=p.target.actor.position.x-p.x,dz=p.target.actor.position.z-p.z,d=Math.hypot(dx,dz),speed=Math.hypot(p.vx,p.vz);if(d>.01){p.vx+=(dx/d*speed-p.vx)*Math.min(1,dt*7);p.vz+=(dz/d*speed-p.vz)*Math.min(1,dt*7);}}p.x+=p.vx*dt;p.z+=p.vz*dt;if(p.enemy){if(distance(p,this.player.position)<.46){this.hurt(p.damage);this.projectiles.splice(i,1);}continue;}for(const e of [...this.enemies]){if(p.hitIds.has(e.id))continue;if(distance(p,e.actor.position)<(e.type==='boss'?1.7:e.type==='tank'?.72:.51)){p.hitIds.add(e.id);this.hitEnemy(e,p.damage,p.critical);if(p.pierce>0){p.pierce--;p.target=null;}else{const idx=this.projectiles.indexOf(p);if(idx>=0)this.projectiles.splice(idx,1);break;}}}}}
  finish(win){if(this.state==='result')return;this.state='result';this.keys.clear();this.audio.stop();this.player.visible=true;this.emit('finish',{win,time:this.time,kills:this.kills,combo:this.bestCombo,score:this.score+Math.floor(this.time)*5+this.perfects*10,level:this.level,perfects:this.perfects});}
  update(dt){
    if(this.state==='menu'){this.player.walk+=dt*.15;for(const f of this.friends)f.actor.walk+=dt*.15;return;}
    if(this.state!=='playing')return;
    this.time=this.audio.ctx?this.audio.now():this.time+dt;this.invincible=Math.max(0,this.invincible-dt);this.dashCd=Math.max(0,this.dashCd-dt);this.barrierCd=Math.max(0,this.barrierCd-dt);this.manualCd=Math.max(0,this.manualCd-dt);this.player.visible=this.invincible>.01&&this.invincible<.72?Math.floor(this.time*18)%3!==0:true;
    const movement=this.moveInput(),magnitude=Math.hypot(movement.x,movement.z);if(magnitude>.12){const angle=Math.atan2(movement.x,movement.z);if(this.lastMoveAngle!==null&&Math.abs(Math.atan2(Math.sin(angle-this.lastMoveAngle),Math.cos(angle-this.lastMoveAngle)))>.7&&this.time-this.lastTurnTime>.4&&this.timing()<.11){this.lastTurnTime=this.time;this.barrier(1);this.energy=clamp(this.energy+2,0,100);this.emit('judge',{text:'SONIC TURN',kind:'perfect'});}this.lastMoveAngle=angle;this.inputDirection.set(movement.x,0,movement.z).normalize();this.player.angle=angle;}
    if(this.dashTimer>0){this.dashTimer-=dt;this.player.position.addScaledVector(this.dashDirection,dt*21);this.world.burst(this.player.position,this.config.color,2,1.5);}else{this.player.position.x+=movement.x*this.speed*dt;this.player.position.z+=movement.z*this.speed*dt;}
    this.player.position.x=clamp(this.player.position.x,-19.5,19.5);this.player.position.z=clamp(this.player.position.z,-16.5,16.5);this.world.constrain?.(this.player.position,.40);this.player.walk+=dt*magnitude*4;
    this.friends.forEach((f,i)=>{const target=i===0?this.player:this.friends[i-1].actor,dir=target.position.clone().sub(f.actor.position);dir.y=0;const d=dir.length();if(d>1.05){dir.normalize();const step=Math.min(d-1.05,dt*(this.speed+Math.max(0,d-2)*3));f.actor.position.addScaledVector(dir,step);f.actor.angle=Math.atan2(dir.x,dir.z);f.actor.walk+=step*4;}});
    let beats=this.audio.schedule();if(!this.audio.ctx){const b=Math.floor(this.time*this.config.bpm/60);if(b!==this.fallbackBeat){this.fallbackBeat=b;beats=[b];}}for(const b of beats)this.onBeat(b);
    const stage=Math.min(4,Math.floor(this.time/30));if(stage!==this.stage){this.stage=stage;this.emit('stage',stage);if(stage>0)this.emit('announcement',{small:['','MOVEMENT II / SYNCOPATION','MOVEMENT III / CRESCENDO','MOVEMENT IV / DISTORTION','MOVEMENT V / RESONANCE'][stage],title:['','切分 · 虚空渐近','渐强 · 保持你的节奏','失真 · 危险正在蔓延','共振 · 最后的前奏'][stage]});}
    if(this.time>=150&&!this.bossSpawned)this.spawnBoss();else if(this.bossSpawned&&!this.boss&&this.state==='playing'){this.bossSpawned=false;this.spawnBoss();}
    if(this.state!=='playing')return;
    if(!this.bossSpawned){this.spawnClock-=dt;if(this.spawnClock<=0){this.spawnClock=[1.35,1,.82,.64,.51][stage];const caps=[14,22,30,38,46];if(this.enemies.length<caps[stage]){const r=Math.random();let type=stage>=3&&r<.13?'tank':stage>=2&&r<.29?'ranged':stage>=1&&r<.48?'charger':'normal';if(type==='ranged'&&this.enemies.filter(e=>e.type==='ranged').length>=5)type='normal';this.spawnEnemy(type);}}}
    this.updateEnemies(dt);if(this.state!=='playing')return;this.updateProjectiles(dt);if(this.state!=='playing')return;
    const radius=2.2+(this.upgrades.magnet||0)*2;let gained=0;for(let i=this.gems.length-1;i>=0;i--){const g=this.gems[i],d=distance(g,this.player.position);if(d<radius){const k=Math.min(1,dt*(6+(radius-d)*3));g.x+=(this.player.position.x-g.x)*k;g.z+=(this.player.position.z-g.z)*k;}if(d<.65){gained+=g.value;this.gems.splice(i,1);this.audio.fx('pickup');}}if(gained)this.addXp(gained);
    this.emit('tick');
  }
  visualProjectiles(){if(!this.upgrades?.orbit)return this.projectiles;const out=this.projectiles.slice();for(let i=0;i<this.upgrades.orbit*2;i++){const a=this.time*2.4+i*TAU/(this.upgrades.orbit*2);out.push({x:this.player.position.x+Math.sin(a)*2.2,z:this.player.position.z+Math.cos(a)*2.2,y:.9,size:.16,color:'#d7eebe',vx:0,vz:1});}return out;}
}
